<h4 class="font2"><i class="typcn typcn-social-facebook-circular"></i> <?php echo $this->__('Facebook fan box') ?></h4>
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/<?php echo Mage::app()->getLocale()->getLocaleCode()?>//all.js#xfbml=1&appId=121855444668430";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-like-box" data-href="http://www.facebook.com/<?php echo Mage::getStoreConfig('evoqueconfig/social_accounts/facebook_profile_name')?>" data-width="282" data-height="320" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>