<h4 class="font2"><i class="typcn typcn-social-twitter-circular"></i> <?php echo $this->__('Twitter') ?></h4>
<a data-chrome="nofooter noheader noborders" data-tweet-limit="<?php echo Mage::getStoreConfig('evoqueconfig/social_accounts/twitter_feeds_count')?>"  data-link-color="#cc0000"    class="twitter-timeline"  href="https://twitter.com/<?php echo Mage::getStoreConfig('evoqueconfig/social_accounts/twitter_account')?>" data-screen-name="<?php echo Mage::getStoreConfig('evoqueconfig/social_accounts/twitter_account')?>"  data-widget-id="395451121138802688"><?php echo $this->__('loading tweets...') ?></a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>






